services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/dashboards

  otelcol:
    image: otel/opentelemetry-collector:0.130.1
    command:
      - --config=/etc/otelcol-config.yaml
    ports:
      - 4317:4317
    volumes:
      - ./otelcol.yaml:/etc/otelcol-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/file_sd:/file_sd
      - prometheus:/prometheus

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093

volumes:
  grafana:
  prometheus:
