apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    url: http://prometheus:9090/prometheus
    isDefault: true
  - name: Jaeger
    type: jaeger
    orgId: 1
    url: http://jaeger:16686/jaeger
